# Семинар 1: знакомство с NumPy


## Немного про Jupyter notebook

Полная документация: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

---
В Jupyter Notebook есть два режима работы: режим _команд_ и режим _редактирования_

_Командный_ режим нужен для того, чтобы взаимодействовать и управлять ячейками (добавлять, удалять, запускать, копировать, ...)

В режиме _редактирования_ вы меняете содержимое ячейки.

Ячейки бывают двух основных типов, _код_ и _разметка_

### Полезные команды

(находясь в командном режиме)

- `a` - добавить пустую ячейку сверху

- `b` - добавить пустую ячейку снизу
- `c` - скопировать текущую ячейку
- `v` - вставить скопированную ячейку
- `d` - удалить текущую ячейку
- `x` - вырезать (удалить и скопировать) текущую ячейку
- `m` - изменить тип выбранной ячейки на "разметка"
- `y` - изменить тип выбранной ячейки на "код"
- `z` - отменить последнее действие


- `Enter` - начать редактировать выбранную ячейку

(будучи в режим редактирования ячейки)
- `esc` - вернуться в командный режим

(будучи в любом режиме)

- `Ctrl + Enter` - запустить выбранную ячейку
- `Shift + Enter` - запустить выбранную ячейку и выбрать следующую

In [96]:
2 + 2

4

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [97]:
import numpy as np

In [98]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [99]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [100]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [101]:
vec.dtype

dtype('int64')

In [102]:
type(vec)

numpy.ndarray

Размер массива:

In [103]:
vec.shape

(3, 2)

Число осей:

In [104]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [105]:
np.sum(vec)

21

In [106]:
np.sum(vec, axis=0)

array([ 9, 12])

In [107]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [108]:
vec.sum()

21

Транспонируем массив:

In [109]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [110]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [111]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [112]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [115]:
vec[:, 1]

array([2, 4, 6])

In [116]:
vec[2, :]

array([5, 6])

In [117]:
vec[1:2, 0]

array([3])

In [118]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

И, наконец - арифметические операции!

In [119]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [120]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [121]:
vec**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [122]:
vec + vec**2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [123]:
vec * vec**2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [124]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [125]:
# vec.dot(vec**2) тут ошибка!

In [126]:
vec.dot((vec**2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [127]:
vec @ (vec**2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [128]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [129]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [130]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Булевы массивы:

In [131]:
is_even = vec % 2 == 0
print(is_even)

[[False  True]
 [False  True]
 [False  True]]


In [132]:
np.sum(is_even)

3

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [133]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [134]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [135]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [136]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [137]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [138]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [139]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Генерация случайных чисел:

In [140]:
np.random.rand(2, 3)

array([[0.33671926, 0.69634152, 0.44107856],
       [0.67951058, 0.2952619 , 0.44636216]])

In [141]:
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [142]:
np.random.randn(3, 2)

array([[ 0.57376143,  0.28772767],
       [-0.23563426,  0.95349024],
       [-1.6896253 , -0.34494271]])

In [143]:
np.random.normal(2, 1, size=3)

array([2.0169049 , 1.48501648, 2.24450929])

In [144]:
np.random.randint(5, 10, size=3)

array([8, 6, 8])

Почему вообще используют `numpy`?

In [145]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [151]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 28.5 s, sys: 22.5 ms, total: 28.5 s
Wall time: 28.8 s


In [147]:
%%time
C = A @ B

CPU times: user 5.74 ms, sys: 0 ns, total: 5.74 ms
Wall time: 12.1 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [150]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.flip(arr), arr[::-1]

(array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1]),
 array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1]))

In [152]:
odd = arr[arr % 2 == 0] # фильтр
np.max(odd), odd.max()

(10, 10)

In [153]:
arr[arr % 2 == 1] = 7
arr

array([ 7,  2,  7,  4,  7,  6,  7,  8,  7, 10])

In [157]:
n = int(input())
#arr = np.arange(n*2)
#arr = arr[arr % 2 == 1]
#arr[::-1]
arr = np.arange(n * 2 - 1, 0, -2)
arr

5


array([9, 7, 5, 3, 1])

In [162]:
n = float(input())
arr = np.arange(0, 5)
res = np.abs(arr - n)
res.argmin(), res.argmax()

1.33


(1, 4)

In [163]:
arr = np.array([4, 6, 0, 1])
pows = np.arange(len(arr), 0 , -1)
ad = np.append(arr / pows, -5)
ad

array([ 1.,  2.,  0.,  1., -5.])

In [ ]:
# №7 ???